# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["misenhower"]
description = "Reports the visitor's IP address and request information."
language = "javascript"
manifest_version = 3
name = "ip.ike.to"
service_id = "eHuhvsyXchZCpAWj63eLJc"

[local_server]

  [local_server.backends]

    [local_server.backends.cloudflare_dns]
      cert_host = "cloudflare-dns.com"
      override_host = "cloudflare-dns.com"
      url = "https://cloudflare-dns.com"

[scripts]
  build = "npm run build"

[setup]

  [setup.backends]

    [setup.backends.cloudflare_dns]
      address = "cloudflare-dns.com"
      description = "Cloudflare DNS-over-HTTPS resolver"
      port = 443
